# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Programozás
author: Csuzdi Domonkos, Farkas Péter, Balogh Csanád, Dr. Bécsi Tamás
logo: logo.png
year: 2025

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/bme-kjit/bsc-programozas
  path_to_book: page
  branch: main

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true

sphinx:
  config:
    html_show_copyright: false

launch_buttons:
  colab_url: "https://colab.research.google.com"